import "./globals.css";

export const metadata = {
  title: "coffee next app",
  description: "Generated by ramin_kp",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>{children}</body>
    </html>
  );
}
